# This file was auto-generated by Fern from our API Definition.

import typing

from .draft_create_to_item_address import DraftCreateToItemAddress

DraftCreateToItem = typing.Union[str, DraftCreateToItemAddress]
