# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawWebhooksClient, RawWebhooksClient
from .types.create_webhooks_response import CreateWebhooksResponse
from .types.get_webhooks_response import GetWebhooksResponse
from .types.list_webhooks_response import ListWebhooksResponse
from .types.rotate_secret_webhooks_response import RotateSecretWebhooksResponse
from .types.update_webhooks_response import UpdateWebhooksResponse
from .types.webhook_create_event_types_item import WebhookCreateEventTypesItem
from .types.webhook_update_event_types_item import WebhookUpdateEventTypesItem

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class WebhooksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWebhooksClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListWebhooksResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListWebhooksResponse
            Webhooks

        Examples
        --------
        from agentmailer import AgentMailer

        client = AgentMailer(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        url: str,
        pod_id: typing.Optional[str] = OMIT,
        inbox_id: typing.Optional[str] = OMIT,
        event_types: typing.Optional[typing.Sequence[WebhookCreateEventTypesItem]] = OMIT,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateWebhooksResponse:
        """
        Parameters
        ----------
        url : str

        pod_id : typing.Optional[str]

        inbox_id : typing.Optional[str]

        event_types : typing.Optional[typing.Sequence[WebhookCreateEventTypesItem]]

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateWebhooksResponse
            Webhook created

        Examples
        --------
        from agentmailer import AgentMailer

        client = AgentMailer(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.create(
            url="url",
        )
        """
        _response = self._raw_client.create(
            url=url,
            pod_id=pod_id,
            inbox_id=inbox_id,
            event_types=event_types,
            description=description,
            request_options=request_options,
        )
        return _response.data

    def get(self, webhook_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetWebhooksResponse:
        """
        Parameters
        ----------
        webhook_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetWebhooksResponse
            Webhook

        Examples
        --------
        from agentmailer import AgentMailer

        client = AgentMailer(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.get(
            webhook_id="webhookId",
        )
        """
        _response = self._raw_client.get(webhook_id, request_options=request_options)
        return _response.data

    def delete(self, webhook_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        webhook_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from agentmailer import AgentMailer

        client = AgentMailer(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.delete(
            webhook_id="webhookId",
        )
        """
        _response = self._raw_client.delete(webhook_id, request_options=request_options)
        return _response.data

    def update(
        self,
        webhook_id: str,
        *,
        url: typing.Optional[str] = OMIT,
        event_types: typing.Optional[typing.Sequence[WebhookUpdateEventTypesItem]] = OMIT,
        description: typing.Optional[str] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateWebhooksResponse:
        """
        Parameters
        ----------
        webhook_id : str

        url : typing.Optional[str]

        event_types : typing.Optional[typing.Sequence[WebhookUpdateEventTypesItem]]

        description : typing.Optional[str]

        enabled : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateWebhooksResponse
            Updated webhook

        Examples
        --------
        from agentmailer import AgentMailer

        client = AgentMailer(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.update(
            webhook_id="webhookId",
        )
        """
        _response = self._raw_client.update(
            webhook_id,
            url=url,
            event_types=event_types,
            description=description,
            enabled=enabled,
            request_options=request_options,
        )
        return _response.data

    def rotate_secret(
        self, webhook_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RotateSecretWebhooksResponse:
        """
        Parameters
        ----------
        webhook_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RotateSecretWebhooksResponse
            New signing secret

        Examples
        --------
        from agentmailer import AgentMailer

        client = AgentMailer(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.rotate_secret(
            webhook_id="webhookId",
        )
        """
        _response = self._raw_client.rotate_secret(webhook_id, request_options=request_options)
        return _response.data


class AsyncWebhooksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWebhooksClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListWebhooksResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListWebhooksResponse
            Webhooks

        Examples
        --------
        import asyncio

        from agentmailer import AsyncAgentMailer

        client = AsyncAgentMailer(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def create(
        self,
        *,
        url: str,
        pod_id: typing.Optional[str] = OMIT,
        inbox_id: typing.Optional[str] = OMIT,
        event_types: typing.Optional[typing.Sequence[WebhookCreateEventTypesItem]] = OMIT,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateWebhooksResponse:
        """
        Parameters
        ----------
        url : str

        pod_id : typing.Optional[str]

        inbox_id : typing.Optional[str]

        event_types : typing.Optional[typing.Sequence[WebhookCreateEventTypesItem]]

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateWebhooksResponse
            Webhook created

        Examples
        --------
        import asyncio

        from agentmailer import AsyncAgentMailer

        client = AsyncAgentMailer(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.create(
                url="url",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            url=url,
            pod_id=pod_id,
            inbox_id=inbox_id,
            event_types=event_types,
            description=description,
            request_options=request_options,
        )
        return _response.data

    async def get(
        self, webhook_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetWebhooksResponse:
        """
        Parameters
        ----------
        webhook_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetWebhooksResponse
            Webhook

        Examples
        --------
        import asyncio

        from agentmailer import AsyncAgentMailer

        client = AsyncAgentMailer(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.get(
                webhook_id="webhookId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(webhook_id, request_options=request_options)
        return _response.data

    async def delete(self, webhook_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        webhook_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from agentmailer import AsyncAgentMailer

        client = AsyncAgentMailer(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.delete(
                webhook_id="webhookId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(webhook_id, request_options=request_options)
        return _response.data

    async def update(
        self,
        webhook_id: str,
        *,
        url: typing.Optional[str] = OMIT,
        event_types: typing.Optional[typing.Sequence[WebhookUpdateEventTypesItem]] = OMIT,
        description: typing.Optional[str] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateWebhooksResponse:
        """
        Parameters
        ----------
        webhook_id : str

        url : typing.Optional[str]

        event_types : typing.Optional[typing.Sequence[WebhookUpdateEventTypesItem]]

        description : typing.Optional[str]

        enabled : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateWebhooksResponse
            Updated webhook

        Examples
        --------
        import asyncio

        from agentmailer import AsyncAgentMailer

        client = AsyncAgentMailer(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.update(
                webhook_id="webhookId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            webhook_id,
            url=url,
            event_types=event_types,
            description=description,
            enabled=enabled,
            request_options=request_options,
        )
        return _response.data

    async def rotate_secret(
        self, webhook_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RotateSecretWebhooksResponse:
        """
        Parameters
        ----------
        webhook_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RotateSecretWebhooksResponse
            New signing secret

        Examples
        --------
        import asyncio

        from agentmailer import AsyncAgentMailer

        client = AsyncAgentMailer(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.rotate_secret(
                webhook_id="webhookId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.rotate_secret(webhook_id, request_options=request_options)
        return _response.data
