// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/aadi-labs/agentmailer-plugins/sdk/go/internal"
	big "math/big"
)

var (
	bootstrapRequestFieldRequestedLocalPart = big.NewInt(1 << 0)
	bootstrapRequestFieldPodName            = big.NewInt(1 << 1)
)

type BootstrapRequest struct {
	RequestedLocalPart *string `json:"requestedLocalPart,omitempty" url:"-"`
	PodName            *string `json:"podName,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (b *BootstrapRequest) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetRequestedLocalPart sets the RequestedLocalPart field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapRequest) SetRequestedLocalPart(requestedLocalPart *string) {
	b.RequestedLocalPart = requestedLocalPart
	b.require(bootstrapRequestFieldRequestedLocalPart)
}

// SetPodName sets the PodName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapRequest) SetPodName(podName *string) {
	b.PodName = podName
	b.require(bootstrapRequestFieldPodName)
}

func (b *BootstrapRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler BootstrapRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*b = BootstrapRequest(body)
	return nil
}

func (b *BootstrapRequest) MarshalJSON() ([]byte, error) {
	type embed BootstrapRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	signUpAgentRequestFieldHumanEmail = big.NewInt(1 << 0)
	signUpAgentRequestFieldUsername   = big.NewInt(1 << 1)
)

type SignUpAgentRequest struct {
	HumanEmail string `json:"human_email" url:"-"`
	Username   string `json:"username" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SignUpAgentRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetHumanEmail sets the HumanEmail field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SignUpAgentRequest) SetHumanEmail(humanEmail string) {
	s.HumanEmail = humanEmail
	s.require(signUpAgentRequestFieldHumanEmail)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SignUpAgentRequest) SetUsername(username string) {
	s.Username = username
	s.require(signUpAgentRequestFieldUsername)
}

func (s *SignUpAgentRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler SignUpAgentRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = SignUpAgentRequest(body)
	return nil
}

func (s *SignUpAgentRequest) MarshalJSON() ([]byte, error) {
	type embed SignUpAgentRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	bootstrapResponseFieldAgent        = big.NewInt(1 << 0)
	bootstrapResponseFieldIdentity     = big.NewInt(1 << 1)
	bootstrapResponseFieldOrganization = big.NewInt(1 << 2)
	bootstrapResponseFieldPod          = big.NewInt(1 << 3)
	bootstrapResponseFieldInbox        = big.NewInt(1 << 4)
	bootstrapResponseFieldCapabilities = big.NewInt(1 << 5)
	bootstrapResponseFieldLimits       = big.NewInt(1 << 6)
	bootstrapResponseFieldLinks        = big.NewInt(1 << 7)
)

type BootstrapResponse struct {
	Agent        *BootstrapResponseAgent        `json:"agent" url:"agent"`
	Identity     *BootstrapResponseIdentity     `json:"identity" url:"identity"`
	Organization *BootstrapResponseOrganization `json:"organization" url:"organization"`
	Pod          *BootstrapResponsePod          `json:"pod" url:"pod"`
	Inbox        *BootstrapResponseInbox        `json:"inbox" url:"inbox"`
	Capabilities *BootstrapResponseCapabilities `json:"capabilities" url:"capabilities"`
	Limits       *BootstrapResponseLimits       `json:"limits" url:"limits"`
	Links        *BootstrapResponseLinks        `json:"links" url:"links"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BootstrapResponse) GetAgent() *BootstrapResponseAgent {
	if b == nil {
		return nil
	}
	return b.Agent
}

func (b *BootstrapResponse) GetIdentity() *BootstrapResponseIdentity {
	if b == nil {
		return nil
	}
	return b.Identity
}

func (b *BootstrapResponse) GetOrganization() *BootstrapResponseOrganization {
	if b == nil {
		return nil
	}
	return b.Organization
}

func (b *BootstrapResponse) GetPod() *BootstrapResponsePod {
	if b == nil {
		return nil
	}
	return b.Pod
}

func (b *BootstrapResponse) GetInbox() *BootstrapResponseInbox {
	if b == nil {
		return nil
	}
	return b.Inbox
}

func (b *BootstrapResponse) GetCapabilities() *BootstrapResponseCapabilities {
	if b == nil {
		return nil
	}
	return b.Capabilities
}

func (b *BootstrapResponse) GetLimits() *BootstrapResponseLimits {
	if b == nil {
		return nil
	}
	return b.Limits
}

func (b *BootstrapResponse) GetLinks() *BootstrapResponseLinks {
	if b == nil {
		return nil
	}
	return b.Links
}

func (b *BootstrapResponse) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BootstrapResponse) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetAgent sets the Agent field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponse) SetAgent(agent *BootstrapResponseAgent) {
	b.Agent = agent
	b.require(bootstrapResponseFieldAgent)
}

// SetIdentity sets the Identity field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponse) SetIdentity(identity *BootstrapResponseIdentity) {
	b.Identity = identity
	b.require(bootstrapResponseFieldIdentity)
}

// SetOrganization sets the Organization field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponse) SetOrganization(organization *BootstrapResponseOrganization) {
	b.Organization = organization
	b.require(bootstrapResponseFieldOrganization)
}

// SetPod sets the Pod field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponse) SetPod(pod *BootstrapResponsePod) {
	b.Pod = pod
	b.require(bootstrapResponseFieldPod)
}

// SetInbox sets the Inbox field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponse) SetInbox(inbox *BootstrapResponseInbox) {
	b.Inbox = inbox
	b.require(bootstrapResponseFieldInbox)
}

// SetCapabilities sets the Capabilities field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponse) SetCapabilities(capabilities *BootstrapResponseCapabilities) {
	b.Capabilities = capabilities
	b.require(bootstrapResponseFieldCapabilities)
}

// SetLimits sets the Limits field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponse) SetLimits(limits *BootstrapResponseLimits) {
	b.Limits = limits
	b.require(bootstrapResponseFieldLimits)
}

// SetLinks sets the Links field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponse) SetLinks(links *BootstrapResponseLinks) {
	b.Links = links
	b.require(bootstrapResponseFieldLinks)
}

func (b *BootstrapResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler BootstrapResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BootstrapResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BootstrapResponse) MarshalJSON() ([]byte, error) {
	type embed BootstrapResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BootstrapResponse) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	bootstrapResponseAgentFieldID        = big.NewInt(1 << 0)
	bootstrapResponseAgentFieldTrustTier = big.NewInt(1 << 1)
)

type BootstrapResponseAgent struct {
	ID        string                          `json:"id" url:"id"`
	TrustTier BootstrapResponseAgentTrustTier `json:"trustTier" url:"trustTier"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BootstrapResponseAgent) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BootstrapResponseAgent) GetTrustTier() BootstrapResponseAgentTrustTier {
	if b == nil {
		return ""
	}
	return b.TrustTier
}

func (b *BootstrapResponseAgent) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BootstrapResponseAgent) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseAgent) SetID(id string) {
	b.ID = id
	b.require(bootstrapResponseAgentFieldID)
}

// SetTrustTier sets the TrustTier field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseAgent) SetTrustTier(trustTier BootstrapResponseAgentTrustTier) {
	b.TrustTier = trustTier
	b.require(bootstrapResponseAgentFieldTrustTier)
}

func (b *BootstrapResponseAgent) UnmarshalJSON(data []byte) error {
	type unmarshaler BootstrapResponseAgent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BootstrapResponseAgent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BootstrapResponseAgent) MarshalJSON() ([]byte, error) {
	type embed BootstrapResponseAgent
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BootstrapResponseAgent) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

type BootstrapResponseAgentTrustTier string

const (
	BootstrapResponseAgentTrustTierBootstrap   BootstrapResponseAgentTrustTier = "bootstrap"
	BootstrapResponseAgentTrustTierVerified    BootstrapResponseAgentTrustTier = "verified"
	BootstrapResponseAgentTrustTierEstablished BootstrapResponseAgentTrustTier = "established"
)

func NewBootstrapResponseAgentTrustTierFromString(s string) (BootstrapResponseAgentTrustTier, error) {
	switch s {
	case "bootstrap":
		return BootstrapResponseAgentTrustTierBootstrap, nil
	case "verified":
		return BootstrapResponseAgentTrustTierVerified, nil
	case "established":
		return BootstrapResponseAgentTrustTierEstablished, nil
	}
	var t BootstrapResponseAgentTrustTier
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (b BootstrapResponseAgentTrustTier) Ptr() *BootstrapResponseAgentTrustTier {
	return &b
}

var (
	bootstrapResponseCapabilitiesFieldReceive       = big.NewInt(1 << 0)
	bootstrapResponseCapabilitiesFieldSend          = big.NewInt(1 << 1)
	bootstrapResponseCapabilitiesFieldImap          = big.NewInt(1 << 2)
	bootstrapResponseCapabilitiesFieldSMTP          = big.NewInt(1 << 3)
	bootstrapResponseCapabilitiesFieldCustomDomains = big.NewInt(1 << 4)
	bootstrapResponseCapabilitiesFieldA2A           = big.NewInt(1 << 5)
)

type BootstrapResponseCapabilities struct {
	Receive       bool `json:"receive" url:"receive"`
	Send          bool `json:"send" url:"send"`
	Imap          bool `json:"imap" url:"imap"`
	SMTP          bool `json:"smtp" url:"smtp"`
	CustomDomains bool `json:"customDomains" url:"customDomains"`
	A2A           bool `json:"a2a" url:"a2a"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BootstrapResponseCapabilities) GetReceive() bool {
	if b == nil {
		return false
	}
	return b.Receive
}

func (b *BootstrapResponseCapabilities) GetSend() bool {
	if b == nil {
		return false
	}
	return b.Send
}

func (b *BootstrapResponseCapabilities) GetImap() bool {
	if b == nil {
		return false
	}
	return b.Imap
}

func (b *BootstrapResponseCapabilities) GetSMTP() bool {
	if b == nil {
		return false
	}
	return b.SMTP
}

func (b *BootstrapResponseCapabilities) GetCustomDomains() bool {
	if b == nil {
		return false
	}
	return b.CustomDomains
}

func (b *BootstrapResponseCapabilities) GetA2A() bool {
	if b == nil {
		return false
	}
	return b.A2A
}

func (b *BootstrapResponseCapabilities) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BootstrapResponseCapabilities) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetReceive sets the Receive field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseCapabilities) SetReceive(receive bool) {
	b.Receive = receive
	b.require(bootstrapResponseCapabilitiesFieldReceive)
}

// SetSend sets the Send field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseCapabilities) SetSend(send bool) {
	b.Send = send
	b.require(bootstrapResponseCapabilitiesFieldSend)
}

// SetImap sets the Imap field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseCapabilities) SetImap(imap bool) {
	b.Imap = imap
	b.require(bootstrapResponseCapabilitiesFieldImap)
}

// SetSMTP sets the SMTP field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseCapabilities) SetSMTP(smtp bool) {
	b.SMTP = smtp
	b.require(bootstrapResponseCapabilitiesFieldSMTP)
}

// SetCustomDomains sets the CustomDomains field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseCapabilities) SetCustomDomains(customDomains bool) {
	b.CustomDomains = customDomains
	b.require(bootstrapResponseCapabilitiesFieldCustomDomains)
}

// SetA2A sets the A2A field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseCapabilities) SetA2A(a2A bool) {
	b.A2A = a2A
	b.require(bootstrapResponseCapabilitiesFieldA2A)
}

func (b *BootstrapResponseCapabilities) UnmarshalJSON(data []byte) error {
	type unmarshaler BootstrapResponseCapabilities
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BootstrapResponseCapabilities(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BootstrapResponseCapabilities) MarshalJSON() ([]byte, error) {
	type embed BootstrapResponseCapabilities
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BootstrapResponseCapabilities) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	bootstrapResponseIdentityFieldID           = big.NewInt(1 << 0)
	bootstrapResponseIdentityFieldHandle       = big.NewInt(1 << 1)
	bootstrapResponseIdentityFieldEmailAddress = big.NewInt(1 << 2)
)

type BootstrapResponseIdentity struct {
	ID           string `json:"id" url:"id"`
	Handle       string `json:"handle" url:"handle"`
	EmailAddress string `json:"emailAddress" url:"emailAddress"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BootstrapResponseIdentity) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BootstrapResponseIdentity) GetHandle() string {
	if b == nil {
		return ""
	}
	return b.Handle
}

func (b *BootstrapResponseIdentity) GetEmailAddress() string {
	if b == nil {
		return ""
	}
	return b.EmailAddress
}

func (b *BootstrapResponseIdentity) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BootstrapResponseIdentity) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseIdentity) SetID(id string) {
	b.ID = id
	b.require(bootstrapResponseIdentityFieldID)
}

// SetHandle sets the Handle field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseIdentity) SetHandle(handle string) {
	b.Handle = handle
	b.require(bootstrapResponseIdentityFieldHandle)
}

// SetEmailAddress sets the EmailAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseIdentity) SetEmailAddress(emailAddress string) {
	b.EmailAddress = emailAddress
	b.require(bootstrapResponseIdentityFieldEmailAddress)
}

func (b *BootstrapResponseIdentity) UnmarshalJSON(data []byte) error {
	type unmarshaler BootstrapResponseIdentity
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BootstrapResponseIdentity(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BootstrapResponseIdentity) MarshalJSON() ([]byte, error) {
	type embed BootstrapResponseIdentity
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BootstrapResponseIdentity) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	bootstrapResponseInboxFieldID      = big.NewInt(1 << 0)
	bootstrapResponseInboxFieldAddress = big.NewInt(1 << 1)
	bootstrapResponseInboxFieldStatus  = big.NewInt(1 << 2)
)

type BootstrapResponseInbox struct {
	ID      string                       `json:"id" url:"id"`
	Address string                       `json:"address" url:"address"`
	Status  BootstrapResponseInboxStatus `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BootstrapResponseInbox) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BootstrapResponseInbox) GetAddress() string {
	if b == nil {
		return ""
	}
	return b.Address
}

func (b *BootstrapResponseInbox) GetStatus() BootstrapResponseInboxStatus {
	if b == nil {
		return ""
	}
	return b.Status
}

func (b *BootstrapResponseInbox) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BootstrapResponseInbox) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseInbox) SetID(id string) {
	b.ID = id
	b.require(bootstrapResponseInboxFieldID)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseInbox) SetAddress(address string) {
	b.Address = address
	b.require(bootstrapResponseInboxFieldAddress)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseInbox) SetStatus(status BootstrapResponseInboxStatus) {
	b.Status = status
	b.require(bootstrapResponseInboxFieldStatus)
}

func (b *BootstrapResponseInbox) UnmarshalJSON(data []byte) error {
	type unmarshaler BootstrapResponseInbox
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BootstrapResponseInbox(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BootstrapResponseInbox) MarshalJSON() ([]byte, error) {
	type embed BootstrapResponseInbox
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BootstrapResponseInbox) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

type BootstrapResponseInboxStatus string

const (
	BootstrapResponseInboxStatusActive BootstrapResponseInboxStatus = "active"
)

func NewBootstrapResponseInboxStatusFromString(s string) (BootstrapResponseInboxStatus, error) {
	switch s {
	case "active":
		return BootstrapResponseInboxStatusActive, nil
	}
	var t BootstrapResponseInboxStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (b BootstrapResponseInboxStatus) Ptr() *BootstrapResponseInboxStatus {
	return &b
}

var (
	bootstrapResponseLimitsFieldMessagesPerDay       = big.NewInt(1 << 0)
	bootstrapResponseLimitsFieldRecipientsPerMessage = big.NewInt(1 << 1)
	bootstrapResponseLimitsFieldAttachmentBytes      = big.NewInt(1 << 2)
)

type BootstrapResponseLimits struct {
	MessagesPerDay       int `json:"messagesPerDay" url:"messagesPerDay"`
	RecipientsPerMessage int `json:"recipientsPerMessage" url:"recipientsPerMessage"`
	AttachmentBytes      int `json:"attachmentBytes" url:"attachmentBytes"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BootstrapResponseLimits) GetMessagesPerDay() int {
	if b == nil {
		return 0
	}
	return b.MessagesPerDay
}

func (b *BootstrapResponseLimits) GetRecipientsPerMessage() int {
	if b == nil {
		return 0
	}
	return b.RecipientsPerMessage
}

func (b *BootstrapResponseLimits) GetAttachmentBytes() int {
	if b == nil {
		return 0
	}
	return b.AttachmentBytes
}

func (b *BootstrapResponseLimits) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BootstrapResponseLimits) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetMessagesPerDay sets the MessagesPerDay field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseLimits) SetMessagesPerDay(messagesPerDay int) {
	b.MessagesPerDay = messagesPerDay
	b.require(bootstrapResponseLimitsFieldMessagesPerDay)
}

// SetRecipientsPerMessage sets the RecipientsPerMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseLimits) SetRecipientsPerMessage(recipientsPerMessage int) {
	b.RecipientsPerMessage = recipientsPerMessage
	b.require(bootstrapResponseLimitsFieldRecipientsPerMessage)
}

// SetAttachmentBytes sets the AttachmentBytes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseLimits) SetAttachmentBytes(attachmentBytes int) {
	b.AttachmentBytes = attachmentBytes
	b.require(bootstrapResponseLimitsFieldAttachmentBytes)
}

func (b *BootstrapResponseLimits) UnmarshalJSON(data []byte) error {
	type unmarshaler BootstrapResponseLimits
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BootstrapResponseLimits(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BootstrapResponseLimits) MarshalJSON() ([]byte, error) {
	type embed BootstrapResponseLimits
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BootstrapResponseLimits) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	bootstrapResponseLinksFieldInbox     = big.NewInt(1 << 0)
	bootstrapResponseLinksFieldMessages  = big.NewInt(1 << 1)
	bootstrapResponseLinksFieldEvents    = big.NewInt(1 << 2)
	bootstrapResponseLinksFieldImap      = big.NewInt(1 << 3)
	bootstrapResponseLinksFieldSMTP      = big.NewInt(1 << 4)
	bootstrapResponseLinksFieldA2A       = big.NewInt(1 << 5)
	bootstrapResponseLinksFieldAgentCard = big.NewInt(1 << 6)
)

type BootstrapResponseLinks struct {
	Inbox     string `json:"inbox" url:"inbox"`
	Messages  string `json:"messages" url:"messages"`
	Events    string `json:"events" url:"events"`
	Imap      string `json:"imap" url:"imap"`
	SMTP      string `json:"smtp" url:"smtp"`
	A2A       string `json:"a2a" url:"a2a"`
	AgentCard string `json:"agentCard" url:"agentCard"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BootstrapResponseLinks) GetInbox() string {
	if b == nil {
		return ""
	}
	return b.Inbox
}

func (b *BootstrapResponseLinks) GetMessages() string {
	if b == nil {
		return ""
	}
	return b.Messages
}

func (b *BootstrapResponseLinks) GetEvents() string {
	if b == nil {
		return ""
	}
	return b.Events
}

func (b *BootstrapResponseLinks) GetImap() string {
	if b == nil {
		return ""
	}
	return b.Imap
}

func (b *BootstrapResponseLinks) GetSMTP() string {
	if b == nil {
		return ""
	}
	return b.SMTP
}

func (b *BootstrapResponseLinks) GetA2A() string {
	if b == nil {
		return ""
	}
	return b.A2A
}

func (b *BootstrapResponseLinks) GetAgentCard() string {
	if b == nil {
		return ""
	}
	return b.AgentCard
}

func (b *BootstrapResponseLinks) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BootstrapResponseLinks) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetInbox sets the Inbox field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseLinks) SetInbox(inbox string) {
	b.Inbox = inbox
	b.require(bootstrapResponseLinksFieldInbox)
}

// SetMessages sets the Messages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseLinks) SetMessages(messages string) {
	b.Messages = messages
	b.require(bootstrapResponseLinksFieldMessages)
}

// SetEvents sets the Events field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseLinks) SetEvents(events string) {
	b.Events = events
	b.require(bootstrapResponseLinksFieldEvents)
}

// SetImap sets the Imap field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseLinks) SetImap(imap string) {
	b.Imap = imap
	b.require(bootstrapResponseLinksFieldImap)
}

// SetSMTP sets the SMTP field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseLinks) SetSMTP(smtp string) {
	b.SMTP = smtp
	b.require(bootstrapResponseLinksFieldSMTP)
}

// SetA2A sets the A2A field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseLinks) SetA2A(a2A string) {
	b.A2A = a2A
	b.require(bootstrapResponseLinksFieldA2A)
}

// SetAgentCard sets the AgentCard field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseLinks) SetAgentCard(agentCard string) {
	b.AgentCard = agentCard
	b.require(bootstrapResponseLinksFieldAgentCard)
}

func (b *BootstrapResponseLinks) UnmarshalJSON(data []byte) error {
	type unmarshaler BootstrapResponseLinks
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BootstrapResponseLinks(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BootstrapResponseLinks) MarshalJSON() ([]byte, error) {
	type embed BootstrapResponseLinks
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BootstrapResponseLinks) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	bootstrapResponseOrganizationFieldID = big.NewInt(1 << 0)
)

type BootstrapResponseOrganization struct {
	ID string `json:"id" url:"id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BootstrapResponseOrganization) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BootstrapResponseOrganization) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BootstrapResponseOrganization) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponseOrganization) SetID(id string) {
	b.ID = id
	b.require(bootstrapResponseOrganizationFieldID)
}

func (b *BootstrapResponseOrganization) UnmarshalJSON(data []byte) error {
	type unmarshaler BootstrapResponseOrganization
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BootstrapResponseOrganization(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BootstrapResponseOrganization) MarshalJSON() ([]byte, error) {
	type embed BootstrapResponseOrganization
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BootstrapResponseOrganization) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	bootstrapResponsePodFieldID   = big.NewInt(1 << 0)
	bootstrapResponsePodFieldName = big.NewInt(1 << 1)
)

type BootstrapResponsePod struct {
	ID   string `json:"id" url:"id"`
	Name string `json:"name" url:"name"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BootstrapResponsePod) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BootstrapResponsePod) GetName() string {
	if b == nil {
		return ""
	}
	return b.Name
}

func (b *BootstrapResponsePod) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BootstrapResponsePod) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponsePod) SetID(id string) {
	b.ID = id
	b.require(bootstrapResponsePodFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BootstrapResponsePod) SetName(name string) {
	b.Name = name
	b.require(bootstrapResponsePodFieldName)
}

func (b *BootstrapResponsePod) UnmarshalJSON(data []byte) error {
	type unmarshaler BootstrapResponsePod
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BootstrapResponsePod(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BootstrapResponsePod) MarshalJSON() ([]byte, error) {
	type embed BootstrapResponsePod
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BootstrapResponsePod) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	signUpAgentResponseFieldStatus                = big.NewInt(1 << 0)
	signUpAgentResponseFieldUsername              = big.NewInt(1 << 1)
	signUpAgentResponseFieldRequestedEmailAddress = big.NewInt(1 << 2)
	signUpAgentResponseFieldApprovalURL           = big.NewInt(1 << 3)
)

type SignUpAgentResponse struct {
	Status                SignUpAgentResponseStatus `json:"status" url:"status"`
	Username              string                    `json:"username" url:"username"`
	RequestedEmailAddress string                    `json:"requestedEmailAddress" url:"requestedEmailAddress"`
	ApprovalURL           string                    `json:"approvalUrl" url:"approvalUrl"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SignUpAgentResponse) GetStatus() SignUpAgentResponseStatus {
	if s == nil {
		return ""
	}
	return s.Status
}

func (s *SignUpAgentResponse) GetUsername() string {
	if s == nil {
		return ""
	}
	return s.Username
}

func (s *SignUpAgentResponse) GetRequestedEmailAddress() string {
	if s == nil {
		return ""
	}
	return s.RequestedEmailAddress
}

func (s *SignUpAgentResponse) GetApprovalURL() string {
	if s == nil {
		return ""
	}
	return s.ApprovalURL
}

func (s *SignUpAgentResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SignUpAgentResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SignUpAgentResponse) SetStatus(status SignUpAgentResponseStatus) {
	s.Status = status
	s.require(signUpAgentResponseFieldStatus)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SignUpAgentResponse) SetUsername(username string) {
	s.Username = username
	s.require(signUpAgentResponseFieldUsername)
}

// SetRequestedEmailAddress sets the RequestedEmailAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SignUpAgentResponse) SetRequestedEmailAddress(requestedEmailAddress string) {
	s.RequestedEmailAddress = requestedEmailAddress
	s.require(signUpAgentResponseFieldRequestedEmailAddress)
}

// SetApprovalURL sets the ApprovalURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SignUpAgentResponse) SetApprovalURL(approvalURL string) {
	s.ApprovalURL = approvalURL
	s.require(signUpAgentResponseFieldApprovalURL)
}

func (s *SignUpAgentResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SignUpAgentResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SignUpAgentResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SignUpAgentResponse) MarshalJSON() ([]byte, error) {
	type embed SignUpAgentResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SignUpAgentResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SignUpAgentResponseStatus string

const (
	SignUpAgentResponseStatusPendingHumanApproval SignUpAgentResponseStatus = "pending_human_approval"
)

func NewSignUpAgentResponseStatusFromString(s string) (SignUpAgentResponseStatus, error) {
	switch s {
	case "pending_human_approval":
		return SignUpAgentResponseStatusPendingHumanApproval, nil
	}
	var t SignUpAgentResponseStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SignUpAgentResponseStatus) Ptr() *SignUpAgentResponseStatus {
	return &s
}
