// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersBillingSelection(t *testing.T) {
	t.Run("SetInboxes", func(t *testing.T) {
		obj := &BillingSelection{}
		var fernTestValueInboxes *int
		obj.SetInboxes(fernTestValueInboxes)
		assert.Equal(t, fernTestValueInboxes, obj.Inboxes)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMonthlyMessages", func(t *testing.T) {
		obj := &BillingSelection{}
		var fernTestValueMonthlyMessages *int
		obj.SetMonthlyMessages(fernTestValueMonthlyMessages)
		assert.Equal(t, fernTestValueMonthlyMessages, obj.MonthlyMessages)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCustomDomains", func(t *testing.T) {
		obj := &BillingSelection{}
		var fernTestValueCustomDomains *int
		obj.SetCustomDomains(fernTestValueCustomDomains)
		assert.Equal(t, fernTestValueCustomDomains, obj.CustomDomains)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetInterval", func(t *testing.T) {
		obj := &BillingSelection{}
		var fernTestValueInterval *BillingSelectionInterval
		obj.SetInterval(fernTestValueInterval)
		assert.Equal(t, fernTestValueInterval, obj.Interval)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitBillingSelection(t *testing.T) {
	t.Run("SetInboxes_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingSelection{}
		var fernTestValueInboxes *int

		// Act
		obj.SetInboxes(fernTestValueInboxes)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMonthlyMessages_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingSelection{}
		var fernTestValueMonthlyMessages *int

		// Act
		obj.SetMonthlyMessages(fernTestValueMonthlyMessages)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCustomDomains_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingSelection{}
		var fernTestValueCustomDomains *int

		// Act
		obj.SetCustomDomains(fernTestValueCustomDomains)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetInterval_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingSelection{}
		var fernTestValueInterval *BillingSelectionInterval

		// Act
		obj.SetInterval(fernTestValueInterval)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersBillingAccount(t *testing.T) {
	t.Run("SetPlan", func(t *testing.T) {
		obj := &BillingAccount{}
		var fernTestValuePlan BillingAccountPlan
		obj.SetPlan(fernTestValuePlan)
		assert.Equal(t, fernTestValuePlan, obj.Plan)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStatus", func(t *testing.T) {
		obj := &BillingAccount{}
		var fernTestValueStatus BillingAccountStatus
		obj.SetStatus(fernTestValueStatus)
		assert.Equal(t, fernTestValueStatus, obj.Status)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCurrentPeriodEnd", func(t *testing.T) {
		obj := &BillingAccount{}
		var fernTestValueCurrentPeriodEnd *time.Time
		obj.SetCurrentPeriodEnd(fernTestValueCurrentPeriodEnd)
		assert.Equal(t, fernTestValueCurrentPeriodEnd, obj.CurrentPeriodEnd)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetInboxLimit", func(t *testing.T) {
		obj := &BillingAccount{}
		var fernTestValueInboxLimit *int
		obj.SetInboxLimit(fernTestValueInboxLimit)
		assert.Equal(t, fernTestValueInboxLimit, obj.InboxLimit)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMonthlySendLimit", func(t *testing.T) {
		obj := &BillingAccount{}
		var fernTestValueMonthlySendLimit *int
		obj.SetMonthlySendLimit(fernTestValueMonthlySendLimit)
		assert.Equal(t, fernTestValueMonthlySendLimit, obj.MonthlySendLimit)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCustomDomainLimit", func(t *testing.T) {
		obj := &BillingAccount{}
		var fernTestValueCustomDomainLimit *int
		obj.SetCustomDomainLimit(fernTestValueCustomDomainLimit)
		assert.Equal(t, fernTestValueCustomDomainLimit, obj.CustomDomainLimit)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetBillingInterval", func(t *testing.T) {
		obj := &BillingAccount{}
		var fernTestValueBillingInterval *BillingAccountBillingInterval
		obj.SetBillingInterval(fernTestValueBillingInterval)
		assert.Equal(t, fernTestValueBillingInterval, obj.BillingInterval)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersBillingAccount(t *testing.T) {
	t.Run("GetPlan", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingAccount{}
		var expected BillingAccountPlan
		obj.Plan = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPlan(), "getter should return the property value")
	})

	t.Run("GetPlan_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BillingAccount
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPlan() // Should return zero value
	})

	t.Run("GetStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingAccount{}
		var expected BillingAccountStatus
		obj.Status = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStatus(), "getter should return the property value")
	})

	t.Run("GetStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BillingAccount
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStatus() // Should return zero value
	})

	t.Run("GetCurrentPeriodEnd", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingAccount{}
		var expected *time.Time
		obj.CurrentPeriodEnd = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCurrentPeriodEnd(), "getter should return the property value")
	})

	t.Run("GetCurrentPeriodEnd_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingAccount{}
		obj.CurrentPeriodEnd = nil

		// Act & Assert
		assert.Nil(t, obj.GetCurrentPeriodEnd(), "getter should return nil when property is nil")
	})

	t.Run("GetCurrentPeriodEnd_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BillingAccount
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCurrentPeriodEnd() // Should return zero value
	})

	t.Run("GetInboxLimit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingAccount{}
		var expected *int
		obj.InboxLimit = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetInboxLimit(), "getter should return the property value")
	})

	t.Run("GetInboxLimit_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingAccount{}
		obj.InboxLimit = nil

		// Act & Assert
		assert.Nil(t, obj.GetInboxLimit(), "getter should return nil when property is nil")
	})

	t.Run("GetInboxLimit_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BillingAccount
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetInboxLimit() // Should return zero value
	})

	t.Run("GetMonthlySendLimit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingAccount{}
		var expected *int
		obj.MonthlySendLimit = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMonthlySendLimit(), "getter should return the property value")
	})

	t.Run("GetMonthlySendLimit_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingAccount{}
		obj.MonthlySendLimit = nil

		// Act & Assert
		assert.Nil(t, obj.GetMonthlySendLimit(), "getter should return nil when property is nil")
	})

	t.Run("GetMonthlySendLimit_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BillingAccount
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMonthlySendLimit() // Should return zero value
	})

	t.Run("GetCustomDomainLimit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingAccount{}
		var expected *int
		obj.CustomDomainLimit = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCustomDomainLimit(), "getter should return the property value")
	})

	t.Run("GetCustomDomainLimit_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingAccount{}
		obj.CustomDomainLimit = nil

		// Act & Assert
		assert.Nil(t, obj.GetCustomDomainLimit(), "getter should return nil when property is nil")
	})

	t.Run("GetCustomDomainLimit_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BillingAccount
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCustomDomainLimit() // Should return zero value
	})

	t.Run("GetBillingInterval", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingAccount{}
		var expected *BillingAccountBillingInterval
		obj.BillingInterval = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetBillingInterval(), "getter should return the property value")
	})

	t.Run("GetBillingInterval_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingAccount{}
		obj.BillingInterval = nil

		// Act & Assert
		assert.Nil(t, obj.GetBillingInterval(), "getter should return nil when property is nil")
	})

	t.Run("GetBillingInterval_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BillingAccount
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBillingInterval() // Should return zero value
	})

}

func TestSettersMarkExplicitBillingAccount(t *testing.T) {
	t.Run("SetPlan_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingAccount{}
		var fernTestValuePlan BillingAccountPlan

		// Act
		obj.SetPlan(fernTestValuePlan)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingAccount{}
		var fernTestValueStatus BillingAccountStatus

		// Act
		obj.SetStatus(fernTestValueStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCurrentPeriodEnd_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingAccount{}
		var fernTestValueCurrentPeriodEnd *time.Time

		// Act
		obj.SetCurrentPeriodEnd(fernTestValueCurrentPeriodEnd)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetInboxLimit_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingAccount{}
		var fernTestValueInboxLimit *int

		// Act
		obj.SetInboxLimit(fernTestValueInboxLimit)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMonthlySendLimit_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingAccount{}
		var fernTestValueMonthlySendLimit *int

		// Act
		obj.SetMonthlySendLimit(fernTestValueMonthlySendLimit)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCustomDomainLimit_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingAccount{}
		var fernTestValueCustomDomainLimit *int

		// Act
		obj.SetCustomDomainLimit(fernTestValueCustomDomainLimit)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetBillingInterval_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingAccount{}
		var fernTestValueBillingInterval *BillingAccountBillingInterval

		// Act
		obj.SetBillingInterval(fernTestValueBillingInterval)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCreateCheckoutBillingResponse(t *testing.T) {
	t.Run("SetURL", func(t *testing.T) {
		obj := &CreateCheckoutBillingResponse{}
		var fernTestValueURL string
		obj.SetURL(fernTestValueURL)
		assert.Equal(t, fernTestValueURL, obj.URL)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCreateCheckoutBillingResponse(t *testing.T) {
	t.Run("GetURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateCheckoutBillingResponse{}
		var expected string
		obj.URL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetURL(), "getter should return the property value")
	})

	t.Run("GetURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateCheckoutBillingResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetURL() // Should return zero value
	})

}

func TestSettersMarkExplicitCreateCheckoutBillingResponse(t *testing.T) {
	t.Run("SetURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateCheckoutBillingResponse{}
		var fernTestValueURL string

		// Act
		obj.SetURL(fernTestValueURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCreatePortalBillingResponse(t *testing.T) {
	t.Run("SetURL", func(t *testing.T) {
		obj := &CreatePortalBillingResponse{}
		var fernTestValueURL string
		obj.SetURL(fernTestValueURL)
		assert.Equal(t, fernTestValueURL, obj.URL)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCreatePortalBillingResponse(t *testing.T) {
	t.Run("GetURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePortalBillingResponse{}
		var expected string
		obj.URL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetURL(), "getter should return the property value")
	})

	t.Run("GetURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreatePortalBillingResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetURL() // Should return zero value
	})

}

func TestSettersMarkExplicitCreatePortalBillingResponse(t *testing.T) {
	t.Run("SetURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePortalBillingResponse{}
		var fernTestValueURL string

		// Act
		obj.SetURL(fernTestValueURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetBillingResponse(t *testing.T) {
	t.Run("SetBilling", func(t *testing.T) {
		obj := &GetBillingResponse{}
		var fernTestValueBilling *BillingAccount
		obj.SetBilling(fernTestValueBilling)
		assert.Equal(t, fernTestValueBilling, obj.Billing)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersGetBillingResponse(t *testing.T) {
	t.Run("GetBilling", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var expected *BillingAccount
		obj.Billing = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetBilling(), "getter should return the property value")
	})

	t.Run("GetBilling_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		obj.Billing = nil

		// Act & Assert
		assert.Nil(t, obj.GetBilling(), "getter should return nil when property is nil")
	})

	t.Run("GetBilling_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetBillingResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBilling() // Should return zero value
	})

}

func TestSettersMarkExplicitGetBillingResponse(t *testing.T) {
	t.Run("SetBilling_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var fernTestValueBilling *BillingAccount

		// Act
		obj.SetBilling(fernTestValueBilling)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingBillingAccount(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BillingAccount{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled BillingAccount
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj BillingAccount
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj BillingAccount
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingCreateCheckoutBillingResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateCheckoutBillingResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CreateCheckoutBillingResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CreateCheckoutBillingResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CreateCheckoutBillingResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingCreatePortalBillingResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePortalBillingResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CreatePortalBillingResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CreatePortalBillingResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CreatePortalBillingResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingGetBillingResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled GetBillingResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj GetBillingResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj GetBillingResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringBillingAccount(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &BillingAccount{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BillingAccount
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringCreateCheckoutBillingResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CreateCheckoutBillingResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateCheckoutBillingResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringCreatePortalBillingResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CreatePortalBillingResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreatePortalBillingResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringGetBillingResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &GetBillingResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetBillingResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumBillingAccountBillingInterval(t *testing.T) {
	t.Run("NewFromString_month", func(t *testing.T) {
		t.Parallel()
		val, err := NewBillingAccountBillingIntervalFromString("month")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, BillingAccountBillingInterval("month"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_year", func(t *testing.T) {
		t.Parallel()
		val, err := NewBillingAccountBillingIntervalFromString("year")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, BillingAccountBillingInterval("year"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewBillingAccountBillingIntervalFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewBillingAccountBillingIntervalFromString("month")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumBillingAccountPlan(t *testing.T) {
	t.Run("NewFromString_free", func(t *testing.T) {
		t.Parallel()
		val, err := NewBillingAccountPlanFromString("free")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, BillingAccountPlan("free"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_developer", func(t *testing.T) {
		t.Parallel()
		val, err := NewBillingAccountPlanFromString("developer")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, BillingAccountPlan("developer"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_startup", func(t *testing.T) {
		t.Parallel()
		val, err := NewBillingAccountPlanFromString("startup")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, BillingAccountPlan("startup"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_enterprise", func(t *testing.T) {
		t.Parallel()
		val, err := NewBillingAccountPlanFromString("enterprise")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, BillingAccountPlan("enterprise"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewBillingAccountPlanFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewBillingAccountPlanFromString("free")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumBillingAccountStatus(t *testing.T) {
	t.Run("NewFromString_active", func(t *testing.T) {
		t.Parallel()
		val, err := NewBillingAccountStatusFromString("active")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, BillingAccountStatus("active"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_trialing", func(t *testing.T) {
		t.Parallel()
		val, err := NewBillingAccountStatusFromString("trialing")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, BillingAccountStatus("trialing"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_past_due", func(t *testing.T) {
		t.Parallel()
		val, err := NewBillingAccountStatusFromString("past_due")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, BillingAccountStatus("past_due"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_paused", func(t *testing.T) {
		t.Parallel()
		val, err := NewBillingAccountStatusFromString("paused")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, BillingAccountStatus("paused"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_canceled", func(t *testing.T) {
		t.Parallel()
		val, err := NewBillingAccountStatusFromString("canceled")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, BillingAccountStatus("canceled"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_unpaid", func(t *testing.T) {
		t.Parallel()
		val, err := NewBillingAccountStatusFromString("unpaid")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, BillingAccountStatus("unpaid"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewBillingAccountStatusFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewBillingAccountStatusFromString("active")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumBillingSelectionInterval(t *testing.T) {
	t.Run("NewFromString_month", func(t *testing.T) {
		t.Parallel()
		val, err := NewBillingSelectionIntervalFromString("month")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, BillingSelectionInterval("month"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_year", func(t *testing.T) {
		t.Parallel()
		val, err := NewBillingSelectionIntervalFromString("year")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, BillingSelectionInterval("year"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewBillingSelectionIntervalFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewBillingSelectionIntervalFromString("month")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesBillingAccount(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &BillingAccount{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BillingAccount
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesCreateCheckoutBillingResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CreateCheckoutBillingResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateCheckoutBillingResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesCreatePortalBillingResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CreatePortalBillingResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreatePortalBillingResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesGetBillingResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &GetBillingResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetBillingResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
