// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersInboxCreate(t *testing.T) {
	t.Run("SetUsername", func(t *testing.T) {
		obj := &InboxCreate{}
		var fernTestValueUsername *string
		obj.SetUsername(fernTestValueUsername)
		assert.Equal(t, fernTestValueUsername, obj.Username)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPodID", func(t *testing.T) {
		obj := &InboxCreate{}
		var fernTestValuePodID *string
		obj.SetPodID(fernTestValuePodID)
		assert.Equal(t, fernTestValuePodID, obj.PodID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDomainID", func(t *testing.T) {
		obj := &InboxCreate{}
		var fernTestValueDomainID *string
		obj.SetDomainID(fernTestValueDomainID)
		assert.Equal(t, fernTestValueDomainID, obj.DomainID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetClientID", func(t *testing.T) {
		obj := &InboxCreate{}
		var fernTestValueClientID *string
		obj.SetClientID(fernTestValueClientID)
		assert.Equal(t, fernTestValueClientID, obj.ClientID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDisplayName", func(t *testing.T) {
		obj := &InboxCreate{}
		var fernTestValueDisplayName *string
		obj.SetDisplayName(fernTestValueDisplayName)
		assert.Equal(t, fernTestValueDisplayName, obj.DisplayName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMetadata", func(t *testing.T) {
		obj := &InboxCreate{}
		var fernTestValueMetadata map[string]*InboxCreateMetadataValue
		obj.SetMetadata(fernTestValueMetadata)
		assert.Equal(t, fernTestValueMetadata, obj.Metadata)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitInboxCreate(t *testing.T) {
	t.Run("SetUsername_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InboxCreate{}
		var fernTestValueUsername *string

		// Act
		obj.SetUsername(fernTestValueUsername)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPodID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InboxCreate{}
		var fernTestValuePodID *string

		// Act
		obj.SetPodID(fernTestValuePodID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDomainID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InboxCreate{}
		var fernTestValueDomainID *string

		// Act
		obj.SetDomainID(fernTestValueDomainID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetClientID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InboxCreate{}
		var fernTestValueClientID *string

		// Act
		obj.SetClientID(fernTestValueClientID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDisplayName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InboxCreate{}
		var fernTestValueDisplayName *string

		// Act
		obj.SetDisplayName(fernTestValueDisplayName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMetadata_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InboxCreate{}
		var fernTestValueMetadata map[string]*InboxCreateMetadataValue

		// Act
		obj.SetMetadata(fernTestValueMetadata)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListInboxesRequest(t *testing.T) {
	t.Run("SetLimit", func(t *testing.T) {
		obj := &ListInboxesRequest{}
		var fernTestValueLimit *int
		obj.SetLimit(fernTestValueLimit)
		assert.Equal(t, fernTestValueLimit, obj.Limit)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPageToken", func(t *testing.T) {
		obj := &ListInboxesRequest{}
		var fernTestValuePageToken *string
		obj.SetPageToken(fernTestValuePageToken)
		assert.Equal(t, fernTestValuePageToken, obj.PageToken)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitListInboxesRequest(t *testing.T) {
	t.Run("SetLimit_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListInboxesRequest{}
		var fernTestValueLimit *int

		// Act
		obj.SetLimit(fernTestValueLimit)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPageToken_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListInboxesRequest{}
		var fernTestValuePageToken *string

		// Act
		obj.SetPageToken(fernTestValuePageToken)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersInbox(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &Inbox{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPodID", func(t *testing.T) {
		obj := &Inbox{}
		var fernTestValuePodID string
		obj.SetPodID(fernTestValuePodID)
		assert.Equal(t, fernTestValuePodID, obj.PodID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAddress", func(t *testing.T) {
		obj := &Inbox{}
		var fernTestValueAddress string
		obj.SetAddress(fernTestValueAddress)
		assert.Equal(t, fernTestValueAddress, obj.Address)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDisplayName", func(t *testing.T) {
		obj := &Inbox{}
		var fernTestValueDisplayName *string
		obj.SetDisplayName(fernTestValueDisplayName)
		assert.Equal(t, fernTestValueDisplayName, obj.DisplayName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetClientID", func(t *testing.T) {
		obj := &Inbox{}
		var fernTestValueClientID *string
		obj.SetClientID(fernTestValueClientID)
		assert.Equal(t, fernTestValueClientID, obj.ClientID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMetadata", func(t *testing.T) {
		obj := &Inbox{}
		var fernTestValueMetadata map[string]*InboxMetadataValue
		obj.SetMetadata(fernTestValueMetadata)
		assert.Equal(t, fernTestValueMetadata, obj.Metadata)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStatus", func(t *testing.T) {
		obj := &Inbox{}
		var fernTestValueStatus InboxStatus
		obj.SetStatus(fernTestValueStatus)
		assert.Equal(t, fernTestValueStatus, obj.Status)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAt", func(t *testing.T) {
		obj := &Inbox{}
		var fernTestValueCreatedAt time.Time
		obj.SetCreatedAt(fernTestValueCreatedAt)
		assert.Equal(t, fernTestValueCreatedAt, obj.CreatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUpdatedAt", func(t *testing.T) {
		obj := &Inbox{}
		var fernTestValueUpdatedAt time.Time
		obj.SetUpdatedAt(fernTestValueUpdatedAt)
		assert.Equal(t, fernTestValueUpdatedAt, obj.UpdatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersInbox(t *testing.T) {
	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Inbox{}
		var expected string
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Inbox
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetPodID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Inbox{}
		var expected string
		obj.PodID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPodID(), "getter should return the property value")
	})

	t.Run("GetPodID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Inbox
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPodID() // Should return zero value
	})

	t.Run("GetAddress", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Inbox{}
		var expected string
		obj.Address = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAddress(), "getter should return the property value")
	})

	t.Run("GetAddress_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Inbox
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAddress() // Should return zero value
	})

	t.Run("GetDisplayName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Inbox{}
		var expected *string
		obj.DisplayName = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDisplayName(), "getter should return the property value")
	})

	t.Run("GetDisplayName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Inbox{}
		obj.DisplayName = nil

		// Act & Assert
		assert.Nil(t, obj.GetDisplayName(), "getter should return nil when property is nil")
	})

	t.Run("GetDisplayName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Inbox
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDisplayName() // Should return zero value
	})

	t.Run("GetClientID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Inbox{}
		var expected *string
		obj.ClientID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetClientID(), "getter should return the property value")
	})

	t.Run("GetClientID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Inbox{}
		obj.ClientID = nil

		// Act & Assert
		assert.Nil(t, obj.GetClientID(), "getter should return nil when property is nil")
	})

	t.Run("GetClientID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Inbox
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetClientID() // Should return zero value
	})

	t.Run("GetMetadata", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Inbox{}
		var expected map[string]*InboxMetadataValue
		obj.Metadata = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMetadata(), "getter should return the property value")
	})

	t.Run("GetMetadata_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Inbox{}
		obj.Metadata = nil

		// Act & Assert
		assert.Nil(t, obj.GetMetadata(), "getter should return nil when property is nil")
	})

	t.Run("GetMetadata_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Inbox
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMetadata() // Should return zero value
	})

	t.Run("GetStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Inbox{}
		var expected InboxStatus
		obj.Status = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStatus(), "getter should return the property value")
	})

	t.Run("GetStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Inbox
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStatus() // Should return zero value
	})

	t.Run("GetCreatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Inbox{}
		var expected time.Time
		obj.CreatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedAt(), "getter should return the property value")
	})

	t.Run("GetCreatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Inbox
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedAt() // Should return zero value
	})

	t.Run("GetUpdatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Inbox{}
		var expected time.Time
		obj.UpdatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUpdatedAt(), "getter should return the property value")
	})

	t.Run("GetUpdatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Inbox
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUpdatedAt() // Should return zero value
	})

}

func TestSettersMarkExplicitInbox(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Inbox{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPodID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Inbox{}
		var fernTestValuePodID string

		// Act
		obj.SetPodID(fernTestValuePodID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAddress_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Inbox{}
		var fernTestValueAddress string

		// Act
		obj.SetAddress(fernTestValueAddress)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDisplayName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Inbox{}
		var fernTestValueDisplayName *string

		// Act
		obj.SetDisplayName(fernTestValueDisplayName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetClientID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Inbox{}
		var fernTestValueClientID *string

		// Act
		obj.SetClientID(fernTestValueClientID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMetadata_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Inbox{}
		var fernTestValueMetadata map[string]*InboxMetadataValue

		// Act
		obj.SetMetadata(fernTestValueMetadata)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Inbox{}
		var fernTestValueStatus InboxStatus

		// Act
		obj.SetStatus(fernTestValueStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Inbox{}
		var fernTestValueCreatedAt time.Time

		// Act
		obj.SetCreatedAt(fernTestValueCreatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUpdatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Inbox{}
		var fernTestValueUpdatedAt time.Time

		// Act
		obj.SetUpdatedAt(fernTestValueUpdatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestGettersInboxMetadataValue(t *testing.T) {
	t.Run("GetString", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InboxMetadataValue{}
		var expected string
		obj.String = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetString(), "getter should return the property value")
	})

	t.Run("GetString_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InboxMetadataValue
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetString() // Should return zero value
	})

	t.Run("GetDouble", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InboxMetadataValue{}
		var expected float64
		obj.Double = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDouble(), "getter should return the property value")
	})

	t.Run("GetDouble_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InboxMetadataValue
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDouble() // Should return zero value
	})

	t.Run("GetBoolean", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InboxMetadataValue{}
		var expected bool
		obj.Boolean = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetBoolean(), "getter should return the property value")
	})

	t.Run("GetBoolean_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InboxMetadataValue
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBoolean() // Should return zero value
	})

}

func TestSettersMailProtocolEndpoint(t *testing.T) {
	t.Run("SetHost", func(t *testing.T) {
		obj := &MailProtocolEndpoint{}
		var fernTestValueHost string
		obj.SetHost(fernTestValueHost)
		assert.Equal(t, fernTestValueHost, obj.Host)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPort", func(t *testing.T) {
		obj := &MailProtocolEndpoint{}
		var fernTestValuePort int
		obj.SetPort(fernTestValuePort)
		assert.Equal(t, fernTestValuePort, obj.Port)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSecurity", func(t *testing.T) {
		obj := &MailProtocolEndpoint{}
		var fernTestValueSecurity MailProtocolEndpointSecurity
		obj.SetSecurity(fernTestValueSecurity)
		assert.Equal(t, fernTestValueSecurity, obj.Security)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersMailProtocolEndpoint(t *testing.T) {
	t.Run("GetHost", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MailProtocolEndpoint{}
		var expected string
		obj.Host = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHost(), "getter should return the property value")
	})

	t.Run("GetHost_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MailProtocolEndpoint
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHost() // Should return zero value
	})

	t.Run("GetPort", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MailProtocolEndpoint{}
		var expected int
		obj.Port = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPort(), "getter should return the property value")
	})

	t.Run("GetPort_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MailProtocolEndpoint
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPort() // Should return zero value
	})

	t.Run("GetSecurity", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MailProtocolEndpoint{}
		var expected MailProtocolEndpointSecurity
		obj.Security = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSecurity(), "getter should return the property value")
	})

	t.Run("GetSecurity_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MailProtocolEndpoint
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSecurity() // Should return zero value
	})

}

func TestSettersMarkExplicitMailProtocolEndpoint(t *testing.T) {
	t.Run("SetHost_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MailProtocolEndpoint{}
		var fernTestValueHost string

		// Act
		obj.SetHost(fernTestValueHost)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPort_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MailProtocolEndpoint{}
		var fernTestValuePort int

		// Act
		obj.SetPort(fernTestValuePort)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSecurity_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MailProtocolEndpoint{}
		var fernTestValueSecurity MailProtocolEndpointSecurity

		// Act
		obj.SetSecurity(fernTestValueSecurity)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCreateInboxesResponse(t *testing.T) {
	t.Run("SetInbox", func(t *testing.T) {
		obj := &CreateInboxesResponse{}
		var fernTestValueInbox *Inbox
		obj.SetInbox(fernTestValueInbox)
		assert.Equal(t, fernTestValueInbox, obj.Inbox)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCreateInboxesResponse(t *testing.T) {
	t.Run("GetInbox", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateInboxesResponse{}
		var expected *Inbox
		obj.Inbox = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetInbox(), "getter should return the property value")
	})

	t.Run("GetInbox_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateInboxesResponse{}
		obj.Inbox = nil

		// Act & Assert
		assert.Nil(t, obj.GetInbox(), "getter should return nil when property is nil")
	})

	t.Run("GetInbox_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateInboxesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetInbox() // Should return zero value
	})

}

func TestSettersMarkExplicitCreateInboxesResponse(t *testing.T) {
	t.Run("SetInbox_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateInboxesResponse{}
		var fernTestValueInbox *Inbox

		// Act
		obj.SetInbox(fernTestValueInbox)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetInboxesResponse(t *testing.T) {
	t.Run("SetInbox", func(t *testing.T) {
		obj := &GetInboxesResponse{}
		var fernTestValueInbox *Inbox
		obj.SetInbox(fernTestValueInbox)
		assert.Equal(t, fernTestValueInbox, obj.Inbox)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersGetInboxesResponse(t *testing.T) {
	t.Run("GetInbox", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetInboxesResponse{}
		var expected *Inbox
		obj.Inbox = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetInbox(), "getter should return the property value")
	})

	t.Run("GetInbox_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetInboxesResponse{}
		obj.Inbox = nil

		// Act & Assert
		assert.Nil(t, obj.GetInbox(), "getter should return nil when property is nil")
	})

	t.Run("GetInbox_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetInboxesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetInbox() // Should return zero value
	})

}

func TestSettersMarkExplicitGetInboxesResponse(t *testing.T) {
	t.Run("SetInbox_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetInboxesResponse{}
		var fernTestValueInbox *Inbox

		// Act
		obj.SetInbox(fernTestValueInbox)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestGettersInboxCreateMetadataValue(t *testing.T) {
	t.Run("GetString", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InboxCreateMetadataValue{}
		var expected string
		obj.String = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetString(), "getter should return the property value")
	})

	t.Run("GetString_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InboxCreateMetadataValue
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetString() // Should return zero value
	})

	t.Run("GetDouble", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InboxCreateMetadataValue{}
		var expected float64
		obj.Double = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDouble(), "getter should return the property value")
	})

	t.Run("GetDouble_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InboxCreateMetadataValue
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDouble() // Should return zero value
	})

	t.Run("GetBoolean", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InboxCreateMetadataValue{}
		var expected bool
		obj.Boolean = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetBoolean(), "getter should return the property value")
	})

	t.Run("GetBoolean_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InboxCreateMetadataValue
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBoolean() // Should return zero value
	})

}

func TestGettersInboxUpdateMetadataValue(t *testing.T) {
	t.Run("GetString", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InboxUpdateMetadataValue{}
		var expected string
		obj.String = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetString(), "getter should return the property value")
	})

	t.Run("GetString_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InboxUpdateMetadataValue
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetString() // Should return zero value
	})

	t.Run("GetDouble", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InboxUpdateMetadataValue{}
		var expected float64
		obj.Double = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDouble(), "getter should return the property value")
	})

	t.Run("GetDouble_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InboxUpdateMetadataValue
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDouble() // Should return zero value
	})

	t.Run("GetBoolean", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InboxUpdateMetadataValue{}
		var expected bool
		obj.Boolean = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetBoolean(), "getter should return the property value")
	})

	t.Run("GetBoolean_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InboxUpdateMetadataValue
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBoolean() // Should return zero value
	})

}

func TestSettersIssueCredentialsInboxesResponse(t *testing.T) {
	t.Run("SetUsername", func(t *testing.T) {
		obj := &IssueCredentialsInboxesResponse{}
		var fernTestValueUsername string
		obj.SetUsername(fernTestValueUsername)
		assert.Equal(t, fernTestValueUsername, obj.Username)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPassword", func(t *testing.T) {
		obj := &IssueCredentialsInboxesResponse{}
		var fernTestValuePassword string
		obj.SetPassword(fernTestValuePassword)
		assert.Equal(t, fernTestValuePassword, obj.Password)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetImap", func(t *testing.T) {
		obj := &IssueCredentialsInboxesResponse{}
		var fernTestValueImap *MailProtocolEndpoint
		obj.SetImap(fernTestValueImap)
		assert.Equal(t, fernTestValueImap, obj.Imap)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSMTP", func(t *testing.T) {
		obj := &IssueCredentialsInboxesResponse{}
		var fernTestValueSMTP *MailProtocolEndpoint
		obj.SetSMTP(fernTestValueSMTP)
		assert.Equal(t, fernTestValueSMTP, obj.SMTP)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersIssueCredentialsInboxesResponse(t *testing.T) {
	t.Run("GetUsername", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &IssueCredentialsInboxesResponse{}
		var expected string
		obj.Username = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUsername(), "getter should return the property value")
	})

	t.Run("GetUsername_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *IssueCredentialsInboxesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUsername() // Should return zero value
	})

	t.Run("GetPassword", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &IssueCredentialsInboxesResponse{}
		var expected string
		obj.Password = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPassword(), "getter should return the property value")
	})

	t.Run("GetPassword_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *IssueCredentialsInboxesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPassword() // Should return zero value
	})

	t.Run("GetImap", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &IssueCredentialsInboxesResponse{}
		var expected *MailProtocolEndpoint
		obj.Imap = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetImap(), "getter should return the property value")
	})

	t.Run("GetImap_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &IssueCredentialsInboxesResponse{}
		obj.Imap = nil

		// Act & Assert
		assert.Nil(t, obj.GetImap(), "getter should return nil when property is nil")
	})

	t.Run("GetImap_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *IssueCredentialsInboxesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetImap() // Should return zero value
	})

	t.Run("GetSMTP", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &IssueCredentialsInboxesResponse{}
		var expected *MailProtocolEndpoint
		obj.SMTP = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSMTP(), "getter should return the property value")
	})

	t.Run("GetSMTP_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &IssueCredentialsInboxesResponse{}
		obj.SMTP = nil

		// Act & Assert
		assert.Nil(t, obj.GetSMTP(), "getter should return nil when property is nil")
	})

	t.Run("GetSMTP_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *IssueCredentialsInboxesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSMTP() // Should return zero value
	})

}

func TestSettersMarkExplicitIssueCredentialsInboxesResponse(t *testing.T) {
	t.Run("SetUsername_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &IssueCredentialsInboxesResponse{}
		var fernTestValueUsername string

		// Act
		obj.SetUsername(fernTestValueUsername)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPassword_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &IssueCredentialsInboxesResponse{}
		var fernTestValuePassword string

		// Act
		obj.SetPassword(fernTestValuePassword)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetImap_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &IssueCredentialsInboxesResponse{}
		var fernTestValueImap *MailProtocolEndpoint

		// Act
		obj.SetImap(fernTestValueImap)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSMTP_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &IssueCredentialsInboxesResponse{}
		var fernTestValueSMTP *MailProtocolEndpoint

		// Act
		obj.SetSMTP(fernTestValueSMTP)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListInboxesResponse(t *testing.T) {
	t.Run("SetInboxes", func(t *testing.T) {
		obj := &ListInboxesResponse{}
		var fernTestValueInboxes []*Inbox
		obj.SetInboxes(fernTestValueInboxes)
		assert.Equal(t, fernTestValueInboxes, obj.Inboxes)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNextPageToken", func(t *testing.T) {
		obj := &ListInboxesResponse{}
		var fernTestValueNextPageToken *string
		obj.SetNextPageToken(fernTestValueNextPageToken)
		assert.Equal(t, fernTestValueNextPageToken, obj.NextPageToken)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersListInboxesResponse(t *testing.T) {
	t.Run("GetInboxes", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListInboxesResponse{}
		var expected []*Inbox
		obj.Inboxes = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetInboxes(), "getter should return the property value")
	})

	t.Run("GetInboxes_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListInboxesResponse{}
		obj.Inboxes = nil

		// Act & Assert
		assert.Nil(t, obj.GetInboxes(), "getter should return nil when property is nil")
	})

	t.Run("GetInboxes_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListInboxesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetInboxes() // Should return zero value
	})

	t.Run("GetNextPageToken", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListInboxesResponse{}
		var expected *string
		obj.NextPageToken = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNextPageToken(), "getter should return the property value")
	})

	t.Run("GetNextPageToken_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListInboxesResponse{}
		obj.NextPageToken = nil

		// Act & Assert
		assert.Nil(t, obj.GetNextPageToken(), "getter should return nil when property is nil")
	})

	t.Run("GetNextPageToken_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListInboxesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNextPageToken() // Should return zero value
	})

}

func TestSettersMarkExplicitListInboxesResponse(t *testing.T) {
	t.Run("SetInboxes_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListInboxesResponse{}
		var fernTestValueInboxes []*Inbox

		// Act
		obj.SetInboxes(fernTestValueInboxes)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNextPageToken_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListInboxesResponse{}
		var fernTestValueNextPageToken *string

		// Act
		obj.SetNextPageToken(fernTestValueNextPageToken)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersUpdateInboxesResponse(t *testing.T) {
	t.Run("SetInbox", func(t *testing.T) {
		obj := &UpdateInboxesResponse{}
		var fernTestValueInbox *Inbox
		obj.SetInbox(fernTestValueInbox)
		assert.Equal(t, fernTestValueInbox, obj.Inbox)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersUpdateInboxesResponse(t *testing.T) {
	t.Run("GetInbox", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateInboxesResponse{}
		var expected *Inbox
		obj.Inbox = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetInbox(), "getter should return the property value")
	})

	t.Run("GetInbox_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateInboxesResponse{}
		obj.Inbox = nil

		// Act & Assert
		assert.Nil(t, obj.GetInbox(), "getter should return nil when property is nil")
	})

	t.Run("GetInbox_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdateInboxesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetInbox() // Should return zero value
	})

}

func TestSettersMarkExplicitUpdateInboxesResponse(t *testing.T) {
	t.Run("SetInbox_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateInboxesResponse{}
		var fernTestValueInbox *Inbox

		// Act
		obj.SetInbox(fernTestValueInbox)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersInboxUpdate(t *testing.T) {
	t.Run("SetDisplayName", func(t *testing.T) {
		obj := &InboxUpdate{}
		var fernTestValueDisplayName *string
		obj.SetDisplayName(fernTestValueDisplayName)
		assert.Equal(t, fernTestValueDisplayName, obj.DisplayName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetClientID", func(t *testing.T) {
		obj := &InboxUpdate{}
		var fernTestValueClientID *string
		obj.SetClientID(fernTestValueClientID)
		assert.Equal(t, fernTestValueClientID, obj.ClientID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMetadata", func(t *testing.T) {
		obj := &InboxUpdate{}
		var fernTestValueMetadata map[string]*InboxUpdateMetadataValue
		obj.SetMetadata(fernTestValueMetadata)
		assert.Equal(t, fernTestValueMetadata, obj.Metadata)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitInboxUpdate(t *testing.T) {
	t.Run("SetDisplayName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InboxUpdate{}
		var fernTestValueDisplayName *string

		// Act
		obj.SetDisplayName(fernTestValueDisplayName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetClientID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InboxUpdate{}
		var fernTestValueClientID *string

		// Act
		obj.SetClientID(fernTestValueClientID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMetadata_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InboxUpdate{}
		var fernTestValueMetadata map[string]*InboxUpdateMetadataValue

		// Act
		obj.SetMetadata(fernTestValueMetadata)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingCreateInboxesResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateInboxesResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CreateInboxesResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CreateInboxesResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CreateInboxesResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingGetInboxesResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetInboxesResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled GetInboxesResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj GetInboxesResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj GetInboxesResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingInbox(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Inbox{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled Inbox
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj Inbox
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj Inbox
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingIssueCredentialsInboxesResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &IssueCredentialsInboxesResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled IssueCredentialsInboxesResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj IssueCredentialsInboxesResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj IssueCredentialsInboxesResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingListInboxesResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListInboxesResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ListInboxesResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ListInboxesResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ListInboxesResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingMailProtocolEndpoint(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MailProtocolEndpoint{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled MailProtocolEndpoint
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj MailProtocolEndpoint
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj MailProtocolEndpoint
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingUpdateInboxesResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateInboxesResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled UpdateInboxesResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj UpdateInboxesResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj UpdateInboxesResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringCreateInboxesResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CreateInboxesResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateInboxesResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringGetInboxesResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &GetInboxesResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetInboxesResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringInbox(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &Inbox{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Inbox
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringIssueCredentialsInboxesResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &IssueCredentialsInboxesResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *IssueCredentialsInboxesResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringListInboxesResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ListInboxesResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListInboxesResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringMailProtocolEndpoint(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &MailProtocolEndpoint{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MailProtocolEndpoint
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringUpdateInboxesResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &UpdateInboxesResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdateInboxesResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumInboxStatus(t *testing.T) {
	t.Run("NewFromString_provisioning", func(t *testing.T) {
		t.Parallel()
		val, err := NewInboxStatusFromString("provisioning")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, InboxStatus("provisioning"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_active", func(t *testing.T) {
		t.Parallel()
		val, err := NewInboxStatusFromString("active")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, InboxStatus("active"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_failed", func(t *testing.T) {
		t.Parallel()
		val, err := NewInboxStatusFromString("failed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, InboxStatus("failed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewInboxStatusFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewInboxStatusFromString("provisioning")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumMailProtocolEndpointSecurity(t *testing.T) {
	t.Run("NewFromString_tls", func(t *testing.T) {
		t.Parallel()
		val, err := NewMailProtocolEndpointSecurityFromString("tls")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MailProtocolEndpointSecurity("tls"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_starttls", func(t *testing.T) {
		t.Parallel()
		val, err := NewMailProtocolEndpointSecurityFromString("starttls")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MailProtocolEndpointSecurity("starttls"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewMailProtocolEndpointSecurityFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewMailProtocolEndpointSecurityFromString("tls")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesCreateInboxesResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CreateInboxesResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateInboxesResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesGetInboxesResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &GetInboxesResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetInboxesResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesInbox(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &Inbox{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Inbox
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesIssueCredentialsInboxesResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &IssueCredentialsInboxesResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *IssueCredentialsInboxesResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesListInboxesResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ListInboxesResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListInboxesResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesMailProtocolEndpoint(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &MailProtocolEndpoint{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MailProtocolEndpoint
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesUpdateInboxesResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &UpdateInboxesResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdateInboxesResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
