# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.idempotency import generate_idempotency_key
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from .types.create_inboxes_response import CreateInboxesResponse
from .types.get_inboxes_response import GetInboxesResponse
from .types.inbox_create_metadata_value import InboxCreateMetadataValue
from .types.inbox_update_metadata_value import InboxUpdateMetadataValue
from .types.issue_credentials_inboxes_response import IssueCredentialsInboxesResponse
from .types.list_inboxes_response import ListInboxesResponse
from .types.update_inboxes_response import UpdateInboxesResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawInboxesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        page_token: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListInboxesResponse]:
        """
        Parameters
        ----------
        limit : typing.Optional[int]

        page_token : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListInboxesResponse]
            Inbox page
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/inboxes",
            method="GET",
            params={
                "limit": limit,
                "page_token": page_token,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListInboxesResponse,
                    parse_obj_as(
                        type_=ListInboxesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        username: typing.Optional[str] = OMIT,
        pod_id: typing.Optional[str] = OMIT,
        domain_id: typing.Optional[str] = OMIT,
        client_id: typing.Optional[str] = OMIT,
        display_name: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, InboxCreateMetadataValue]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CreateInboxesResponse]:
        """
        Parameters
        ----------
        username : typing.Optional[str]

        pod_id : typing.Optional[str]

        domain_id : typing.Optional[str]

        client_id : typing.Optional[str]

        display_name : typing.Optional[str]

        metadata : typing.Optional[typing.Dict[str, InboxCreateMetadataValue]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateInboxesResponse]
            Existing idempotent result
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/inboxes",
            method="POST",
            json={
                "username": username,
                "podId": pod_id,
                "domainId": domain_id,
                "clientId": client_id,
                "displayName": display_name,
                "metadata": convert_and_respect_annotation_metadata(
                    object_=metadata, annotation=typing.Dict[str, InboxCreateMetadataValue], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
                "Idempotency-Key": generate_idempotency_key(),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateInboxesResponse,
                    parse_obj_as(
                        type_=CreateInboxesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(
        self, inbox_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GetInboxesResponse]:
        """
        Parameters
        ----------
        inbox_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetInboxesResponse]
            Inbox
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/inboxes/{encode_path_param(inbox_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetInboxesResponse,
                    parse_obj_as(
                        type_=GetInboxesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete(self, inbox_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[None]:
        """
        Parameters
        ----------
        inbox_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/inboxes/{encode_path_param(inbox_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update(
        self,
        inbox_id: str,
        *,
        display_name: typing.Optional[str] = OMIT,
        client_id: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[InboxUpdateMetadataValue]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[UpdateInboxesResponse]:
        """
        Parameters
        ----------
        inbox_id : str

        display_name : typing.Optional[str]

        client_id : typing.Optional[str]

        metadata : typing.Optional[typing.Dict[str, typing.Optional[InboxUpdateMetadataValue]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[UpdateInboxesResponse]
            Updated inbox
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/inboxes/{encode_path_param(inbox_id)}",
            method="PATCH",
            json={
                "displayName": display_name,
                "clientId": client_id,
                "metadata": convert_and_respect_annotation_metadata(
                    object_=metadata,
                    annotation=typing.Optional[typing.Dict[str, typing.Optional[InboxUpdateMetadataValue]]],
                    direction="write",
                ),
            },
            headers={
                "content-type": "application/json",
                "Idempotency-Key": generate_idempotency_key(),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UpdateInboxesResponse,
                    parse_obj_as(
                        type_=UpdateInboxesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def issue_credentials(
        self, inbox_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[IssueCredentialsInboxesResponse]:
        """
        Parameters
        ----------
        inbox_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[IssueCredentialsInboxesResponse]
            Mailbox credentials
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/inboxes/{encode_path_param(inbox_id)}/credentials",
            method="POST",
            headers={
                "Idempotency-Key": generate_idempotency_key(),
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IssueCredentialsInboxesResponse,
                    parse_obj_as(
                        type_=IssueCredentialsInboxesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawInboxesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        page_token: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListInboxesResponse]:
        """
        Parameters
        ----------
        limit : typing.Optional[int]

        page_token : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListInboxesResponse]
            Inbox page
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/inboxes",
            method="GET",
            params={
                "limit": limit,
                "page_token": page_token,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListInboxesResponse,
                    parse_obj_as(
                        type_=ListInboxesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        username: typing.Optional[str] = OMIT,
        pod_id: typing.Optional[str] = OMIT,
        domain_id: typing.Optional[str] = OMIT,
        client_id: typing.Optional[str] = OMIT,
        display_name: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, InboxCreateMetadataValue]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CreateInboxesResponse]:
        """
        Parameters
        ----------
        username : typing.Optional[str]

        pod_id : typing.Optional[str]

        domain_id : typing.Optional[str]

        client_id : typing.Optional[str]

        display_name : typing.Optional[str]

        metadata : typing.Optional[typing.Dict[str, InboxCreateMetadataValue]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateInboxesResponse]
            Existing idempotent result
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/inboxes",
            method="POST",
            json={
                "username": username,
                "podId": pod_id,
                "domainId": domain_id,
                "clientId": client_id,
                "displayName": display_name,
                "metadata": convert_and_respect_annotation_metadata(
                    object_=metadata, annotation=typing.Dict[str, InboxCreateMetadataValue], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
                "Idempotency-Key": generate_idempotency_key(),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateInboxesResponse,
                    parse_obj_as(
                        type_=CreateInboxesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self, inbox_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GetInboxesResponse]:
        """
        Parameters
        ----------
        inbox_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetInboxesResponse]
            Inbox
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/inboxes/{encode_path_param(inbox_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetInboxesResponse,
                    parse_obj_as(
                        type_=GetInboxesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete(
        self, inbox_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Parameters
        ----------
        inbox_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/inboxes/{encode_path_param(inbox_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update(
        self,
        inbox_id: str,
        *,
        display_name: typing.Optional[str] = OMIT,
        client_id: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[InboxUpdateMetadataValue]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[UpdateInboxesResponse]:
        """
        Parameters
        ----------
        inbox_id : str

        display_name : typing.Optional[str]

        client_id : typing.Optional[str]

        metadata : typing.Optional[typing.Dict[str, typing.Optional[InboxUpdateMetadataValue]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[UpdateInboxesResponse]
            Updated inbox
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/inboxes/{encode_path_param(inbox_id)}",
            method="PATCH",
            json={
                "displayName": display_name,
                "clientId": client_id,
                "metadata": convert_and_respect_annotation_metadata(
                    object_=metadata,
                    annotation=typing.Optional[typing.Dict[str, typing.Optional[InboxUpdateMetadataValue]]],
                    direction="write",
                ),
            },
            headers={
                "content-type": "application/json",
                "Idempotency-Key": generate_idempotency_key(),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UpdateInboxesResponse,
                    parse_obj_as(
                        type_=UpdateInboxesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def issue_credentials(
        self, inbox_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[IssueCredentialsInboxesResponse]:
        """
        Parameters
        ----------
        inbox_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[IssueCredentialsInboxesResponse]
            Mailbox credentials
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/inboxes/{encode_path_param(inbox_id)}/credentials",
            method="POST",
            headers={
                "Idempotency-Key": generate_idempotency_key(),
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IssueCredentialsInboxesResponse,
                    parse_obj_as(
                        type_=IssueCredentialsInboxesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
