# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.channel_message_send import ChannelMessageSend
from .raw_client import AsyncRawChannelMessagesClient, RawChannelMessagesClient
from .types.list_channel_messages_request_channel import ListChannelMessagesRequestChannel
from .types.list_channel_messages_response import ListChannelMessagesResponse
from .types.send_channel_messages_response import SendChannelMessagesResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ChannelMessagesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawChannelMessagesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawChannelMessagesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawChannelMessagesClient
        """
        return self._raw_client

    def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        page_token: typing.Optional[str] = None,
        endpoint_id: typing.Optional[str] = None,
        conversation_id: typing.Optional[str] = None,
        channel: typing.Optional[ListChannelMessagesRequestChannel] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListChannelMessagesResponse:
        """
        List human-channel messages

        Parameters
        ----------
        limit : typing.Optional[int]

        page_token : typing.Optional[str]

        endpoint_id : typing.Optional[str]

        conversation_id : typing.Optional[str]

        channel : typing.Optional[ListChannelMessagesRequestChannel]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListChannelMessagesResponse
            Channel message page

        Examples
        --------
        from agentmailer import AgentMailer

        client = AgentMailer(
            api_key="YOUR_API_KEY",
        )
        client.channel_messages.list()
        """
        _response = self._raw_client.list(
            limit=limit,
            page_token=page_token,
            endpoint_id=endpoint_id,
            conversation_id=conversation_id,
            channel=channel,
            request_options=request_options,
        )
        return _response.data

    def send(
        self,
        *,
        idempotency_key: str,
        request: ChannelMessageSend,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SendChannelMessagesResponse:
        """
        Sends through an assigned SMS, MMS, RCS, WhatsApp, or outbound voice endpoint. Supports RCS rich cards and replies, plus WhatsApp media and reply buttons. All non-template WhatsApp messages require a recipient message within the last 24 hours; otherwise use an approved template.

        Parameters
        ----------
        idempotency_key : str
            Stable caller-generated key used to make retries safe without duplicating the operation.

        request : ChannelMessageSend

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SendChannelMessagesResponse
            Existing idempotent result

        Examples
        --------
        import datetime

        from agentmailer import (
            AgentMailer,
            ChannelMessageSend_Sms,
            ChannelMessageSendSmsConsent,
            ChannelMessageSendSmsContent,
        )

        client = AgentMailer(
            api_key="YOUR_API_KEY",
        )
        client.channel_messages.send(
            idempotency_key="Idempotency-Key",
            request=ChannelMessageSend_Sms(
                endpoint_id="endpointId",
                to="to",
                consent=ChannelMessageSendSmsConsent(
                    basis="explicit",
                    captured_at=datetime.datetime.fromisoformat(
                        "2024-01-15 09:30:00+00:00",
                    ),
                    reference="reference",
                ),
                content=ChannelMessageSendSmsContent(
                    type="text",
                    body="body",
                ),
            ),
        )
        """
        _response = self._raw_client.send(
            idempotency_key=idempotency_key, request=request, request_options=request_options
        )
        return _response.data


class AsyncChannelMessagesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawChannelMessagesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawChannelMessagesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawChannelMessagesClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        page_token: typing.Optional[str] = None,
        endpoint_id: typing.Optional[str] = None,
        conversation_id: typing.Optional[str] = None,
        channel: typing.Optional[ListChannelMessagesRequestChannel] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListChannelMessagesResponse:
        """
        List human-channel messages

        Parameters
        ----------
        limit : typing.Optional[int]

        page_token : typing.Optional[str]

        endpoint_id : typing.Optional[str]

        conversation_id : typing.Optional[str]

        channel : typing.Optional[ListChannelMessagesRequestChannel]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListChannelMessagesResponse
            Channel message page

        Examples
        --------
        import asyncio

        from agentmailer import AsyncAgentMailer

        client = AsyncAgentMailer(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channel_messages.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            limit=limit,
            page_token=page_token,
            endpoint_id=endpoint_id,
            conversation_id=conversation_id,
            channel=channel,
            request_options=request_options,
        )
        return _response.data

    async def send(
        self,
        *,
        idempotency_key: str,
        request: ChannelMessageSend,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SendChannelMessagesResponse:
        """
        Sends through an assigned SMS, MMS, RCS, WhatsApp, or outbound voice endpoint. Supports RCS rich cards and replies, plus WhatsApp media and reply buttons. All non-template WhatsApp messages require a recipient message within the last 24 hours; otherwise use an approved template.

        Parameters
        ----------
        idempotency_key : str
            Stable caller-generated key used to make retries safe without duplicating the operation.

        request : ChannelMessageSend

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SendChannelMessagesResponse
            Existing idempotent result

        Examples
        --------
        import asyncio
        import datetime

        from agentmailer import (
            AsyncAgentMailer,
            ChannelMessageSend_Sms,
            ChannelMessageSendSmsConsent,
            ChannelMessageSendSmsContent,
        )

        client = AsyncAgentMailer(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channel_messages.send(
                idempotency_key="Idempotency-Key",
                request=ChannelMessageSend_Sms(
                    endpoint_id="endpointId",
                    to="to",
                    consent=ChannelMessageSendSmsConsent(
                        basis="explicit",
                        captured_at=datetime.datetime.fromisoformat(
                            "2024-01-15 09:30:00+00:00",
                        ),
                        reference="reference",
                    ),
                    content=ChannelMessageSendSmsContent(
                        type="text",
                        body="body",
                    ),
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.send(
            idempotency_key=idempotency_key, request=request, request_options=request_options
        )
        return _response.data
