// This file was auto-generated by Fern from our API Definition.

import * as AgentMailer from "../../../index.js";

export interface UpdateChannelEndpointsResponse {
    endpoint: AgentMailer.ChannelEndpoint;
}
