// This file was auto-generated by Fern from our API Definition.

import * as AgentMailer from "../index.js";

export type ChannelMessageSendWhatsappContent = 
    | AgentMailer.ChannelMessageSendWhatsappContent.Text
    | AgentMailer.ChannelMessageSendWhatsappContent.Template
    | AgentMailer.ChannelMessageSendWhatsappContent.Media
    | AgentMailer.ChannelMessageSendWhatsappContent.Buttons;

export namespace ChannelMessageSendWhatsappContent {
    export interface Text {
        type: "text";
        body: string;
    }

    export interface Template {
        type: "template";
        name: string;
        languageCode: string;
        components?: Record<string, unknown>[] | undefined;
    }

    export interface Media {
        type: "media";
        kind: ChannelMessageSendWhatsappContentMedia.Kind;
        attachmentId: string;
    }

    export namespace ChannelMessageSendWhatsappContentMedia {
        export const Kind = {
                Image: "image",
                Video: "video",
                Audio: "audio",
                Document: "document"
            } as const;
        export type Kind = typeof Kind[keyof typeof Kind];
    }

    export interface Buttons {
        type: "buttons";
        body: string;
        buttons: ChannelMessageSendWhatsappContentButtons.Buttons.Item[];
    }

    export namespace ChannelMessageSendWhatsappContentButtons {
        export type Buttons = Buttons.Item[];

        export namespace Buttons {
            export interface Item {
                id: string;
                title: string;
            }
        }
    }
}
