// This file was auto-generated by Fern from our API Definition.

export interface Draft {
    to: Draft.To.Item[];
    cc?: Draft.Cc.Item[] | undefined;
    bcc?: Draft.Bcc.Item[] | undefined;
    replyTo?: Draft.ReplyTo.Item[] | undefined;
    subject?: string | undefined;
    text?: string | undefined;
    html?: string | undefined;
    headers?: Record<string, string> | undefined;
    attachments: Draft.Attachments.Item[];
    replyToMessageId?: string | undefined;
    forwardMessageId?: string | undefined;
    sendAt?: (string | null) | undefined;
    id: string;
    inboxId: string;
    createdAt: string;
    updatedAt: string;
    sendStatus: Draft.SendStatus | null;
}

export namespace Draft {
    export type To = To.Item[];

    export namespace To {
        export type Item =
            | string
            | {
                  address: string;
                  name?: string | undefined;
              };
    }

    export type Cc = Cc.Item[];

    export namespace Cc {
        export type Item =
            | string
            | {
                  address: string;
                  name?: string | undefined;
              };
    }

    export type Bcc = Bcc.Item[];

    export namespace Bcc {
        export type Item =
            | string
            | {
                  address: string;
                  name?: string | undefined;
              };
    }

    export type ReplyTo = ReplyTo.Item[];

    export namespace ReplyTo {
        export type Item =
            | string
            | {
                  address: string;
                  name?: string | undefined;
              };
    }

    export type Attachments = Attachments.Item[];

    export namespace Attachments {
        export type Item =
            | {
                  filename: string;
                  contentType?: unknown | undefined;
                  content: string;
                  contentId?: string | undefined;
                  disposition: "attachment" | "inline";
              }
            | {
                  attachmentId: string;
                  contentId?: string | undefined;
                  disposition: "attachment" | "inline";
              };
    }

    export const SendStatus = {
        Scheduled: "scheduled",
        Sending: "sending",
        Failed: "failed",
    } as const;
    export type SendStatus = (typeof SendStatus)[keyof typeof SendStatus];
}
