# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .a2a_agent_card_supported_interfaces_item_protocol_binding import (
    A2AAgentCardSupportedInterfacesItemProtocolBinding,
)
from .a2a_agent_card_supported_interfaces_item_protocol_version import (
    A2AAgentCardSupportedInterfacesItemProtocolVersion,
)


class A2AAgentCardSupportedInterfacesItem(UniversalBaseModel):
    url: str
    protocol_binding: typing_extensions.Annotated[
        A2AAgentCardSupportedInterfacesItemProtocolBinding,
        FieldMetadata(alias="protocolBinding"),
        pydantic.Field(alias="protocolBinding"),
    ]
    protocol_version: typing_extensions.Annotated[
        A2AAgentCardSupportedInterfacesItemProtocolVersion,
        FieldMetadata(alias="protocolVersion"),
        pydantic.Field(alias="protocolVersion"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
