# This file was auto-generated by Fern from our API Definition.

import typing

ChannelMessageSafetyModelStatus = typing.Union[
    typing.Literal["not_configured", "skipped", "completed", "unavailable"], typing.Any
]
