# This file was auto-generated by Fern from our API Definition.

import typing

ChannelRecipientPermissionConsentBasis = typing.Union[
    typing.Literal["explicit", "transactional_relationship", "inbound_keyword"], typing.Any
]
