# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .channel_message_send_sms_consent_basis import ChannelMessageSendSmsConsentBasis


class ChannelMessageSendSmsConsent(UniversalBaseModel):
    basis: ChannelMessageSendSmsConsentBasis
    captured_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="capturedAt"), pydantic.Field(alias="capturedAt")
    ]
    reference: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
