# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawBillingClient, RawBillingClient
from .types.billing_selection_interval import BillingSelectionInterval
from .types.create_checkout_billing_response import CreateCheckoutBillingResponse
from .types.create_portal_billing_response import CreatePortalBillingResponse
from .types.get_billing_response import GetBillingResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class BillingClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawBillingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawBillingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawBillingClient
        """
        return self._raw_client

    def get(self, *, request_options: typing.Optional[RequestOptions] = None) -> GetBillingResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetBillingResponse
            Billing account

        Examples
        --------
        from agentmailer import AgentMailer

        client = AgentMailer(
            api_key="YOUR_API_KEY",
        )
        client.billing.get()
        """
        _response = self._raw_client.get(request_options=request_options)
        return _response.data

    def create_checkout(
        self,
        *,
        inboxes: typing.Optional[int] = OMIT,
        monthly_messages: typing.Optional[int] = OMIT,
        custom_domains: typing.Optional[int] = OMIT,
        interval: typing.Optional[BillingSelectionInterval] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateCheckoutBillingResponse:
        """
        Parameters
        ----------
        inboxes : typing.Optional[int]

        monthly_messages : typing.Optional[int]

        custom_domains : typing.Optional[int]

        interval : typing.Optional[BillingSelectionInterval]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateCheckoutBillingResponse
            Checkout session

        Examples
        --------
        from agentmailer import AgentMailer

        client = AgentMailer(
            api_key="YOUR_API_KEY",
        )
        client.billing.create_checkout()
        """
        _response = self._raw_client.create_checkout(
            inboxes=inboxes,
            monthly_messages=monthly_messages,
            custom_domains=custom_domains,
            interval=interval,
            request_options=request_options,
        )
        return _response.data

    def create_portal(self, *, request_options: typing.Optional[RequestOptions] = None) -> CreatePortalBillingResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePortalBillingResponse
            Customer portal

        Examples
        --------
        from agentmailer import AgentMailer

        client = AgentMailer(
            api_key="YOUR_API_KEY",
        )
        client.billing.create_portal()
        """
        _response = self._raw_client.create_portal(request_options=request_options)
        return _response.data


class AsyncBillingClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawBillingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawBillingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawBillingClient
        """
        return self._raw_client

    async def get(self, *, request_options: typing.Optional[RequestOptions] = None) -> GetBillingResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetBillingResponse
            Billing account

        Examples
        --------
        import asyncio

        from agentmailer import AsyncAgentMailer

        client = AsyncAgentMailer(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.billing.get()


        asyncio.run(main())
        """
        _response = await self._raw_client.get(request_options=request_options)
        return _response.data

    async def create_checkout(
        self,
        *,
        inboxes: typing.Optional[int] = OMIT,
        monthly_messages: typing.Optional[int] = OMIT,
        custom_domains: typing.Optional[int] = OMIT,
        interval: typing.Optional[BillingSelectionInterval] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateCheckoutBillingResponse:
        """
        Parameters
        ----------
        inboxes : typing.Optional[int]

        monthly_messages : typing.Optional[int]

        custom_domains : typing.Optional[int]

        interval : typing.Optional[BillingSelectionInterval]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateCheckoutBillingResponse
            Checkout session

        Examples
        --------
        import asyncio

        from agentmailer import AsyncAgentMailer

        client = AsyncAgentMailer(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.billing.create_checkout()


        asyncio.run(main())
        """
        _response = await self._raw_client.create_checkout(
            inboxes=inboxes,
            monthly_messages=monthly_messages,
            custom_domains=custom_domains,
            interval=interval,
            request_options=request_options,
        )
        return _response.data

    async def create_portal(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CreatePortalBillingResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePortalBillingResponse
            Customer portal

        Examples
        --------
        import asyncio

        from agentmailer import AsyncAgentMailer

        client = AsyncAgentMailer(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.billing.create_portal()


        asyncio.run(main())
        """
        _response = await self._raw_client.create_portal(request_options=request_options)
        return _response.data
