// This file was auto-generated by Fern from our API Definition.

import { AgentMailerClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AgentClient", () => {
    test("bootstrap", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailerClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            agent: { id: "id", trustTier: "bootstrap" },
            identity: { id: "id", handle: "handle", emailAddress: "emailAddress" },
            organization: { id: "id" },
            pod: { id: "id", name: "name" },
            inbox: { id: "id", address: "address", status: "active" },
            capabilities: { receive: true, send: true, imap: true, smtp: true, customDomains: true, a2a: true },
            limits: { messagesPerDay: 1, recipientsPerMessage: 1, attachmentBytes: 1 },
            links: {
                inbox: "inbox",
                messages: "messages",
                events: "events",
                imap: "imap",
                smtp: "smtp",
                a2a: "a2a",
                agentCard: "agentCard",
            },
        };

        server
            .mockEndpoint()
            .post("/v1/agent/bootstrap")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agent.bootstrap();
        expect(response).toEqual(rawResponseBody);
    });

    test("signUp", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailerClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { human_email: "human_email", username: "username" };
        const rawResponseBody = {
            status: "pending_human_approval",
            username: "username",
            requestedEmailAddress: "requestedEmailAddress",
            approvalUrl: "approvalUrl",
        };

        server
            .mockEndpoint()
            .post("/v1/agent/sign-up")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agent.signUp({
            human_email: "human_email",
            username: "username",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
