// This file was auto-generated by Fern from our API Definition.

import { AgentMailerClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("BillingClient", () => {
    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailerClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            billing: {
                plan: "free",
                status: "active",
                stripeCustomerId: "stripeCustomerId",
                stripeSubscriptionId: "stripeSubscriptionId",
                currentPeriodEnd: "2024-01-15T09:30:00Z",
                inboxLimit: 1,
                monthlySendLimit: 1,
                customDomainLimit: 1,
                billingInterval: "month",
            },
        };

        server.mockEndpoint().get("/v1/billing").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.billing.get();
        expect(response).toEqual(rawResponseBody);
    });

    test("createCheckout", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailerClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { url: "url" };

        server
            .mockEndpoint()
            .post("/v1/billing/checkout")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.createCheckout();
        expect(response).toEqual(rawResponseBody);
    });

    test("createPortal", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailerClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { url: "url" };

        server
            .mockEndpoint()
            .post("/v1/billing/portal")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.createPortal();
        expect(response).toEqual(rawResponseBody);
    });
});
