// This file was auto-generated by Fern from our API Definition.

import { AgentMailerClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("DraftsClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailerClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            drafts: [
                {
                    to: ["to"],
                    cc: ["cc"],
                    bcc: ["bcc"],
                    replyTo: ["replyTo"],
                    subject: "subject",
                    text: "text",
                    html: "html",
                    headers: { key: "value" },
                    attachments: [],
                    replyToMessageId: "replyToMessageId",
                    forwardMessageId: "forwardMessageId",
                    sendAt: "2024-01-15T09:30:00Z",
                    id: "id",
                    inboxId: "inboxId",
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                    sendStatus: "scheduled",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v1/inboxes/inboxId/drafts")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.drafts.list("inboxId");
        expect(response).toEqual(rawResponseBody);
    });

    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailerClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            draft: {
                to: ["to"],
                cc: ["cc"],
                bcc: ["bcc"],
                replyTo: ["replyTo"],
                subject: "subject",
                text: "text",
                html: "html",
                headers: { key: "value" },
                attachments: [],
                replyToMessageId: "replyToMessageId",
                forwardMessageId: "forwardMessageId",
                sendAt: "2024-01-15T09:30:00Z",
                id: "id",
                inboxId: "inboxId",
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                sendStatus: "scheduled",
            },
        };

        server
            .mockEndpoint()
            .post("/v1/inboxes/inboxId/drafts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.drafts.create("inboxId");
        expect(response).toEqual(rawResponseBody);
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailerClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            draft: {
                to: ["to"],
                cc: ["cc"],
                bcc: ["bcc"],
                replyTo: ["replyTo"],
                subject: "subject",
                text: "text",
                html: "html",
                headers: { key: "value" },
                attachments: [],
                replyToMessageId: "replyToMessageId",
                forwardMessageId: "forwardMessageId",
                sendAt: "2024-01-15T09:30:00Z",
                id: "id",
                inboxId: "inboxId",
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                sendStatus: "scheduled",
            },
        };

        server
            .mockEndpoint()
            .get("/v1/inboxes/inboxId/drafts/draftId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.drafts.get("inboxId", "draftId");
        expect(response).toEqual(rawResponseBody);
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailerClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/v1/inboxes/inboxId/drafts/draftId").respondWith().statusCode(200).build();

        const response = await client.drafts.delete("inboxId", "draftId");
        expect(response).toEqual(undefined);
    });

    test("update", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailerClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            draft: {
                to: ["to"],
                cc: ["cc"],
                bcc: ["bcc"],
                replyTo: ["replyTo"],
                subject: "subject",
                text: "text",
                html: "html",
                headers: { key: "value" },
                attachments: [],
                replyToMessageId: "replyToMessageId",
                forwardMessageId: "forwardMessageId",
                sendAt: "2024-01-15T09:30:00Z",
                id: "id",
                inboxId: "inboxId",
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                sendStatus: "scheduled",
            },
        };

        server
            .mockEndpoint()
            .patch("/v1/inboxes/inboxId/drafts/draftId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.drafts.update("inboxId", "draftId");
        expect(response).toEqual(rawResponseBody);
    });

    test("send", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailerClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            message: {
                id: "id",
                inboxId: "inboxId",
                threadId: "threadId",
                direction: "inbound",
                status: "queued",
                from: "from",
                to: ["to"],
                cc: ["cc"],
                bcc: ["bcc"],
                replyTo: ["replyTo"],
                subject: "subject",
                text: "text",
                html: "html",
                extractedText: "extractedText",
                extractedHtml: "extractedHtml",
                headers: { key: "value" },
                inReplyTo: "inReplyTo",
                references: ["references"],
                attachments: [
                    {
                        id: "id",
                        filename: "filename",
                        contentType: "contentType",
                        size: 1,
                        contentId: null,
                        disposition: "attachment",
                    },
                ],
                createdAt: "2024-01-15T09:30:00Z",
                sentAt: "2024-01-15T09:30:00Z",
                receivedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .post("/v1/inboxes/inboxId/drafts/draftId/send")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.drafts.send("inboxId", "draftId");
        expect(response).toEqual(rawResponseBody);
    });
});
