// This file was auto-generated by Fern from our API Definition.

import { AgentMailerClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ListsClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailerClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            lists: [
                {
                    podId: "podId",
                    name: "name",
                    kind: "allow",
                    id: "id",
                    entries: [],
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
        };

        server.mockEndpoint().get("/v1/lists").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.lists.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailerClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { podId: "podId", name: "name", kind: "allow" };
        const rawResponseBody = {
            list: {
                podId: "podId",
                name: "name",
                kind: "allow",
                id: "id",
                entries: [],
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .post("/v1/lists")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.lists.create({
            podId: "podId",
            name: "name",
            kind: "allow",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailerClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/v1/lists/listId").respondWith().statusCode(200).build();

        const response = await client.lists.delete("listId");
        expect(response).toEqual(undefined);
    });

    test("addEntry", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailerClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { addressPattern: "addressPattern" };
        const rawResponseBody = {
            list: {
                podId: "podId",
                name: "name",
                kind: "allow",
                id: "id",
                entries: [],
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .post("/v1/lists/listId/entries")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.lists.addEntry("listId", {
            addressPattern: "addressPattern",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("removeEntry", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailerClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            list: {
                podId: "podId",
                name: "name",
                kind: "allow",
                id: "id",
                entries: [],
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .delete("/v1/lists/listId/entries")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.lists.removeEntry("listId");
        expect(response).toEqual(rawResponseBody);
    });
});
